# Generated by Django 5.1.7 on 2025-10-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rayon',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rayons', to='users.boutique'),
        ),
        migrations.AddField(
            model_name='produit',
            name='rayon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='shop.rayon'),
        ),
    ]
