# Generated by Django 5.1.7 on 2025-10-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommandeBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('Attente', 'attente'), ('Préparation', 'préparation'), ('Livraison', 'livraison'), ('Réçu', 'réçu'), ('Annulé', 'annulé')], default='attente', max_length=15)),
                ('heure_de_commande', models.DateTimeField(auto_now_add=True)),
                ('jour', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('prix_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('Attente', 'attente'), ('Préparation', 'préparation'), ('Livraison', 'livraison'), ('Réçu', 'réçu'), ('Annulé', 'annulé')], default='attente', max_length=15)),
                ('heure_de_commande', models.DateTimeField(auto_now_add=True)),
                ('jour', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('prix_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Commande_Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_total', models.IntegerField()),
                ('rate', models.FloatField(default=0.0)),
                ('rating_count', models.FloatField(default=0.0)),
                ('rating_sum', models.FloatField(default=0.0)),
                ('plat_commander', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_plat', to='e_commerce.menu_plat')),
            ],
        ),
    ]
