# Generated by Django 5.1.7 on 2025-10-12 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_commerce', '0002_initial'),
        ('localisation', '0002_initial'),
        ('shop', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeboutique',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_produits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commandeboutique',
            name='produits',
            field=models.ManyToManyField(through='localisation.Commande_Produit', to='shop.produit'),
        ),
        migrations.AddField(
            model_name='commande_produit',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_produit', to='localisation.commandeboutique'),
        ),
        migrations.AddField(
            model_name='commanderestaurant',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commanderestaurant',
            name='plats',
            field=models.ManyToManyField(related_name='commandes', through='localisation.Commande_Plat', to='e_commerce.menu_plat'),
        ),
        migrations.AddField(
            model_name='commande_plat',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_plat', to='localisation.commanderestaurant'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='localisation.commanderestaurant'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='users.livreur'),
        ),
        migrations.AddField(
            model_name='commanderestaurant',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='localisation.position'),
        ),
        migrations.AddField(
            model_name='commandeboutique',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_produits', to='localisation.position'),
        ),
    ]
