# Generated by Django 5.1.7 on 2025-10-12 16:28

import cloudinary.models
import datetime
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tel', models.IntegerField()),
                ('profile', models.CharField(choices=[('client', 'Client'), ('entreprise', 'Entreprise'), ('livreur', 'Livreur')], default='client', max_length=15)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=190, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=10)),
                ('a_restaurant', models.BooleanField(default=False)),
                ('a_boutique', models.BooleanField(default=False)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='image')),
                ('quartier', models.CharField(blank=True, default='', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=15)),
                ('ouverture', models.TimeField(default=datetime.time(8, 0))),
                ('fermeture', models.TimeField(default=datetime.time(18, 0))),
                ('horaire_hebdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='users.horairehebdomadaire')),
            ],
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_ouvert', models.BooleanField(default=False)),
                ('rate', models.FloatField(default=0.0)),
                ('rating_count', models.FloatField(default=0.0)),
                ('rating_sum', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to=settings.AUTH_USER_MODEL)),
                ('horaire', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to='users.horairehebdomadaire')),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30)),
                ('description', models.TextField(blank='', default='')),
                ('est_a_personne', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('occupé', 'Occupé'), ('libre', 'Libre')], default='libre', max_length=15)),
                ('rate', models.FloatField(default=0.0)),
                ('rating_count', models.FloatField(default=0.0)),
                ('rating_sum', models.FloatField(default=0.0)),
                ('entreprise', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livreurs', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_plat', models.CharField(max_length=100)),
                ('rate', models.FloatField(default=0.0)),
                ('rating_count', models.FloatField(default=0.0)),
                ('rating_sum', models.FloatField(default=0.0)),
                ('est_ouvert', models.BooleanField(default=False)),
                ('horaire', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='users.horairehebdomadaire')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
