# Generated by Django 5.1.7 on 2025-10-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='couleur',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
