# Generated by Django 5.1.7 on 2025-10-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('montant', models.FloatField()),
                ('status', models.CharField(default='en_attente', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
