# Generated by Django 5.1.7 on 2025-10-12 16:28

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MenuHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MenuStatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MenuStatique_Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='aucune description')),
                ('prix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.0)),
                ('is_avialable', models.BooleanField(default=True)),
                ('rating_count', models.FloatField(default=0.0)),
                ('rating_sum', models.FloatField(default=0.0)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='aucune description')),
                ('prix', models.IntegerField()),
                ('menu', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_plat', to='e_commerce.menu')),
            ],
        ),
    ]
