# Generated by Django 5.1.7 on 2025-10-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_commerce', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuhebdomadaire',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_hebdo', to='users.restaurant'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_hebdo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='e_commerce.menuhebdomadaire'),
        ),
        migrations.AddField(
            model_name='menustatique',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_statique', to='users.restaurant'),
        ),
        migrations.AddField(
            model_name='menustatique_plat',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plats', to='e_commerce.menustatique'),
        ),
        migrations.AddField(
            model_name='restaurant_plat',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.plat'),
        ),
        migrations.AddField(
            model_name='restaurant_plat',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.restaurant'),
        ),
        migrations.AddField(
            model_name='plat',
            name='restaurants',
            field=models.ManyToManyField(related_name='plats', through='e_commerce.Restaurant_Plat', to='users.restaurant'),
        ),
        migrations.AddField(
            model_name='menustatique_plat',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.restaurant_plat'),
        ),
        migrations.AddField(
            model_name='menu_plat',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.restaurant_plat'),
        ),
        migrations.AddField(
            model_name='menu',
            name='plats',
            field=models.ManyToManyField(related_name='menus', through='e_commerce.Menu_Plat', to='e_commerce.restaurant_plat'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant_plat',
            unique_together={('restaurant', 'plat')},
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('menu_hebdo', 'jour'), name='unique_menuhebdo_jour'),
        ),
    ]
